---
driver:
  name: vagrant
  driver_config:
  require_chef_omnibus: 12.2.1
  customize:
    memory: 1024 

provisioner:
  name: chef_solo

platforms:
- name: centos-6.5
  driver_config:
    box: centos65
    box_url: "#{ENV['HOME']}/Centos6.5.box"
    network:
    - ["forwarded_port", {guest: 80, host: 8080}]
    - ["forwarded_port", {guest: 443, host: 8543}]
    - ["private_network", {ip: "33.33.33.10"}]

suites:
  - name: default
    run_list:
    - recipe[wordpressCoobookDemo::default]
    attributes:
